### PR TITLE
Fix derived eq for arrays

### LINKED ISSUE #71: `eq` derived for `array` raises
```OCaml
# type x = int array [@@deriving eq] ;;
type x = int array
val equal_x : x -> x -> bool = <fun>
# equal_x [| |] [| |] ;;
Exception: Invalid_argument "index out of bounds".
```

Will PR a fix.

### PR DESCRIPTION
**Pull request by pqwy**
Fixes #71. It's a case of misplaced parentheses. :smile:

### CODE REVIEW

**Comment by whitequark** [comment]
Such a silly bug, for sure. Thanks!

**Comment by whitequark** [comment]
Mind adding a test?

**Comment by pqwy** [comment]
Sure, sec.

**Comment by pqwy** [comment]
Amended. I stopped short of adding tests for all prims. Could be useful IMHO.

**Pull request merged**
