### PR TITLE
new plugin: ppx_deriving_lens

### PR DESCRIPTION
**Pull request by didier-wenzek**
This proposed plugin adds a lens to each field of a record
To be used with https://github.com/avsm/ocaml-lens/

### CODE REVIEW

**Comment by Drup** [comment]
Why put it in ppx_deriving ? It should go in the lens package.

**Comment by didier-wenzek** [comment]
I think that the implementation is by far more related to ppx_deriving than to lens.
I agree that the plugin can be used if no Lens package is defined with the proper signature.
An alternative is to put the code in a specific package as for ppx_deriving_yojson.
Is it what you mean ?

**Comment by c-cube** [comment]
I agree that it probably should go in `lens`. There might be other lens types — e.g. using (possibly first-class) modules — that would need a different ppx to work.

**Comment by whitequark** [comment]
While I think the plugin is great, the policy of the `ppx_deriving` package is that it will only depend on stdlib (I consider stdlib to include `ppx_tools` and `ocamlfind`). Thus `deriving(lens)` cannot be added. I agree with other commenters that it should preferably go in the `lens` package, or in `ppx_deriving_lens` if that is not possible.

**Comment by rgrinberg** [comment]
@didier-wenzek How come you aren't using the more maintained ocaml-lens fork? https://github.com/pdonadeo/ocaml-lens

**Comment by didier-wenzek** [comment]
@rgrinberg You are right the opam package references the fork of pdonadeo.

**Comment by didier-wenzek** [comment]
Done, the plugin has been merged into https://github.com/pdonadeo/ocaml-lens

**Comment by Drup** [comment]
Happy ending ! :3

**Pull request closed without merging**
