### PR TITLE
Very crude attempt at fixing create #65

### PR DESCRIPTION
**Pull request by rgrinberg**
So I managed to hack something together that seems to work but I need some
guidance on how to proceed. Currently I've changed `create` to asses the scope
of the changes but now I'm not sure how to proceed with a real `make` plugin.
Seems like almost all of the code will be the same between the 2 plugins, how
should I share the code between the two?

### CODE REVIEW

**Comment by whitequark** [comment]
LGTM. Just copy the code instead (with modifications), since we're not really interested in improving the old version it in any way, and please add a deprecation warning to the emitted code of `[@deriving create]`.

**Comment by rgrinberg** [comment]
@whitequark I've created ppx_deriving.make but I'm not so sure about the deprecation warning for the emitted code. It's likely that sers of ppx_deriving.create are exposing those functions to users of their own code and just deprecating seems excessive all of a sudden. Are we sure about this?

**Comment by whitequark** [comment]
Hmmmm true. Just replace it in README then.

**Comment by arvidj** [comment]
Sorry for digging this up. I just tried to figure out form which opam library the `create` deriver comes from. I was pretty confused since it wasn't mentioned in the README.md of `ppx_deriving`. Then I was very confused when I saw that there were both `make` and `create`, with no discussion of the difference. I think mentioning `create` as a deprecated deriver in the README.md would be a good idea.

**Comment by gasche** [comment]
Done: https://github.com/ocaml-ppx/ppx_deriving/commit/077b26d11947dbdfb8f6aca3944c8c3d97ed37ac.

**Comment by arvidj** [comment]
> Done: [077b26d](https://github.com/ocaml-ppx/ppx_deriving/commit/077b26d11947dbdfb8f6aca3944c8c3d97ed37ac).

Thanks!

**Pull request merged**
